#!/bin/zsh

LINES=$(wc ~/.tips | awk '{$1=$1;print}' | cut -d' ' -f1)
MY_RANDOM=$(shuf -i 1-$LINES -n1)
PHRASE=$(tail -n$MY_RANDOM ~/.tips | head -n1)

echo "Tip of the day..."
echo "======================================"
echo "$PHRASE"
